apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    nodePort: 30002
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
