apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon-set-primeiro
  labels:
    app: "nginx"
spec:
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: RollingUpdate
