apiVersion: v1
kind: PersistentVolume
metadata:
  name: primeiro-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  # - ReadWriteOnce
  # - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/giropops
    server: 172.31.53.159 # usar uma máquina q eu criar na nuvem
    readOnly: false